baseurl = "/"
languageCode = "en-US"
title = "Portfolio"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "ethanwindsweb.png"
  author = "Ethan Pieniazek"
  description = "Website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "ethanpieniazek@utexas.edu"

## Main Menu
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 200
  url = "pieniazek_resume_site.pdf"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 300
  url = "/projects/"
[[menu.main]]
  name = "teaching philosophy"
  identifier = "teaching philosophy"
  weight = 100
  url = "teaching_philosophy_web.pdf"
[[menu.main]]
  name = "teaching activities"
  identifier = "teaching activities"
  weight = 100
  url = "teachingact"
